### PR TITLE
Query processing branch

### PR DESCRIPTION
**Pull request by TSabnis**
Hi,

I have created only one header file for query processing (query-processing.h) under integration folder which has all the classes for query processing including QueryTree and QueryResult. This will make it easy to include header files.

### CODE REVIEW

**Comment by manasaV92** [comment]
Can you not make modifications to existing files or create new files inside the integration folder? If you need to add new header or definitions files that should be done inside your query-processing folder, you could create `query-processing/integration` and the suitable files. This will help us during the integration process. Accepting changes you have currently made will disrupt our integration process. Please let us know after you have made these changes to the current PR, so we can merge them.

**Comment by TSabnis** [comment]
Hi Manasa,

We were facing compiling issues because of the multiple include statements
and circular dependencies therefore there was a need to merge them into a
single header file for simplicity. The only impact should be on the query
parser right? Going forward we won't need to change any file structure in
the integration folder except the query-processing.h file. Please let me
know if you are ok with this change, else we will revert to the original
structure but I don't think that will build correctly.

Hi Nikhil,
Please delete the geometry-collection.cpp from the integration folder of
our branch.
Please also remove the include statements for this file if any and please
reply to this email once the changes are done so that the Integration team
can merge the code.

Thank you.
Regards,
Tejal

**Comment by manasaV92** [comment]
The changes to `query-processing.h` are fine with us. We will merge this PR once the other changes are reverted.

**Comment by nvementala** [comment]
Hi Manasa,

I have moved geometry-collection.cpp from integration folder to query processing folder and changed the header files accordingly. Can you please check now and let me know if you need anything else.

**Comment by hariniravichandran** [comment]
We will merge after the changes to `src/integration/geometry.h` are reverted.

**Comment by nvementala** [comment]
Removed header guards, This is the only change we have made in that.

**Pull request merged**
